name: CI
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  test:
    name: "Run unit tests"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run tests
        run: npm run test
